FROM --platform=${TARGETPLATFORM} gcr.io/distroless/static-debian13:nonroot

ARG TARGETPLATFORM

ARG VERSION=v0.0.0
ENV VERSION=${VERSION}

ARG UID=65532
ENV UID=${UID}

ARG GID=65532
ENV GID=${GID}

USER ${UID}:${GID}

WORKDIR /app

COPY --chown=${UID}:${GID} --chmod=0755 ${TARGETPLATFORM}/schedulord /app/schedulord

ENTRYPOINT ["/app/schedulord"]
