FROM alpine:3.24.1

ARG TARGETPLATFORM

ARG VERSION=v0.0.0
ENV VERSION=${VERSION}

ARG USER=schedulord
ENV USER=${USER}

ARG GROUP=schedulord
ENV GROUP=${GROUP}

ARG UID=1000
ENV UID=${UID}

ARG GID=1000
ENV GID=${GID}

RUN set -eux && \
    addgroup -g ${GID} ${GROUP} && \
    adduser -D -u ${UID} -G ${GROUP} ${USER} && \
    mkdir /app && \
    chown -R ${USER}:${GROUP} /app && \
    true

RUN set -eux && \
    apk add --no-cache \
      ca-certificates \
      tzdata && \
    true

USER ${USER}:${GROUP}

WORKDIR /app

COPY --chown=${USER}:${GROUP} --chmod=0755 ${TARGETPLATFORM}/schedulord /app/schedulord

ENTRYPOINT ["/app/schedulord"]
